---
apiVersion: apps/v1
kind: Deployment  
metadata:  
  name: pod-pvp
spec: 
  replicas: 4
  selector:
    matchLabels:
      app: pvp
  template:
    metadata:
      labels:
        app: pvp
    spec:
      containers:
        - name: pvp-server
          image: k8s_test_pvp:v1
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: env-pvp
