---
apiVersion: v1
kind: Service
metadata:
  name: pvp-server
  labels:
    app: pvp-server
spec:
  # type: LoadBalancer
  # ports:
  #   - port: 8081
  clusterIP: None
  selector:
    app: pvp
---
apiVersion: v1
kind: Service
metadata:
  name: game-server
  labels:
    app: game-server
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: game